[settings]
experimental = true
npm.package_manager = "pnpm"

[[env]]
_.source = { path = ".mise/set_node_path_var.sh", tools = true }
[[env]]
_.source = { path = ".mise/set_helm_plugins_var.sh", tools = true }
CGO_ENABLED = 1

[tools]
jq = "1.8.1"
uv = "0.10.0"
shellcheck = "0.11.0"
"pipx:podman-compose" = "1.5.0"
kube-linter = "0.7.6"
kubeconform = "0.7.0"
pnpm = "10.29.2"
helm = "4.1.0"
"pipx:checkov" = "3.2.495"
editorconfig-checker = "3.6.0"
"github:sass/dart-sass" = "1.92.1"
hadolint = "2.14.0"
hugo-extended = "0.150.0"
jujutsu = "0.33.0"
just = "1.46.0"
pre-commit = "4.5.0"
trivy = "0.69.0"
vale = "3.13.0"
yamllint = "1.38.0"
node = "24.13.0"
go = "1.26.0"
python = "3.14.2"
"npm:@prantlf/jsonlint" = "17.0.0"
"npm:renovate" = "43.22.0"
"npm:semantic-release" = "25.0.2"
"npm:@semantic-release-plus/docker" = "3.1.3"
"npm:@semantic-release/changelog" = "6.0.3"
"npm:@semantic-release/exec" = "7.1.0"
"npm:@semantic-release/git" = "10.0.1"

[tools."http:helm-kubeconform"]
version = "0.2.0"
url = "https://github.com/jtyr/kubeconform-helm/archive/refs/tags/v{{version}}.tar.gz"
