---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
  pr-checks:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    env:
      MISE_CACHE_DIR: /home/devcontaineruser/.cache/mise
      MISE_CONFIG_DIR: /home/devcontaineruser/.config/mise
      MISE_STATE_DIR: /home/devcontaineruser/.local/state/mise
      MISE_DATA_DIR: /home/devcontaineruser/.local/share/mise
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Setup mise
        uses: jdx/mise-action@v3
      - name: Lint
        run: just lint
      - name: Test
        run: just test
      - name: Security scan
        run: just security-scan
  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    permissions:
      packages: write
    needs:
      - prepare
      - pr-checks
    if: always()
