---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  prepare:
    uses: ./.github/workflows/prepare-devcontainer-image.yaml
    permissions:
      contents: read
      packages: write
  lint:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Run pre-commit to lint
        run: |
          just lint
  build:
    needs: prepare
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-devcontainer:${{ github.sha }}-${{github.run_id}}
      options: --user root --privileged
    permissions:
      contents: read
      packages: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Configure git
        run: |
          git config --global --add safe.directory '*'
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
      - name: Build
        run: |
          just build
      - name: Perform test
        run: |
          just test
      - name: Run securiy scan
        run: |
          just security-scan
  cleanup:
    uses: ./.github/workflows/cleanup-devcontainer-image.yaml
    permissions:
      packages: write
    needs:
      - prepare
      - lint
      - build
    if: always()
